network:
  path_to_network_params: "trained_models/shoes_consistent/shoes_consistent_M_background_0.500_3_15K_training/015001.pth"

template: "templates/shoes/shoes_consistent_M_background_0.500_3_15K_training_descriptor_template.pcd"